components {
  id: "script_v3"
  component: "/example/box2d_dynamic_scale_v3.script"
}
components {
  id: "script_v2"
  component: "/example/box2d_dynamic_scale_v2.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"body_soft\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 80.0\n"
  "  y: 80.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/textures/textures.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.2\n"
  "restitution: 0.2\n"
  "group: \"block\"\n"
  "mask: \"block\"\n"
  "mask: \"wall\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"box\"\n"
  "  }\n"
  "  data: 40.0\n"
  "  data: 40.0\n"
  "  data: 10.0\n"
  "}\n"
  "linear_damping: 0.2\n"
  "angular_damping: 0.1\n"
  ""
}
