embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/models/crate.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"colormap\"\n"
  "  material: \"/assets/materials/unlit.material\"\n"
  "  textures {\n"
  "    sampler: \"texture0\"\n"
  "    texture: \"/assets/models/Textures/colormap.png\"\n"
  "  }\n"
  "}\n"
  ""
  position {
    y: -0.25
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.9\n"
  "restitution: 0.3\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.25\n"
  "  data: 0.25\n"
  "  data: 0.25\n"
  "}\n"
  "linear_damping: 0.001\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
