rm -rf ./render_camera/assets/text24.font
rm -rf ./animation_spine/assets/text24.font
rm -rf ./material_noise/assets/text24.font
rm -rf ./animation_chained_flipbook/assets/text24.font
rm -rf ./gui_healthbar/assets/text24.font
rm -rf ./collection_proxy/assets/text24.font
rm -rf ./gui_stencil/assets/text24.font
rm -rf ./physics_knockback/assets/text24.font
rm -rf ./movement_look_at/assets/text24.font
rm -rf ./movement_look_rotation/assets/text24.font
rm -rf ./tilemap_collisions/assets/text24.font
rm -rf ./physics_pendulum/assets/text24.font
rm -rf ./mesh_triangle/assets/text24.font
rm -rf ./debug_profile/assets/text24.font
rm -rf ./particles_particlefx/assets/text24.font
rm -rf ./model_cubemap/assets/text24.font
rm -rf ./sprite_tint/assets/text24.font
rm -rf ./movement_move_forward/assets/text24.font
rm -rf ./material_screenspace/assets/text24.font
rm -rf ./gui_get_set_texture/assets/text24.font
rm -rf ./render_orbit_camera/assets/text24.font
rm -rf ./material_vertexcolor/assets/text24.font
rm -rf ./material_unlit/assets/text24.font
rm -rf ./physics_raycast/assets/text24.font
rm -rf ./sound_fade_in_out/assets/text24.font
rm -rf ./material_uvgradient/assets/text24.font
rm -rf ./sound_panning/assets/text24.font
rm -rf ./input_text/assets/text24.font
rm -rf ./basics_message_passing/assets/text24.font
rm -rf ./animation_euler_rotation/assets/text24.font
rm -rf ./gui_slice9/assets/text24.font
rm -rf ./file_sys_save_load/assets/text24.font
rm -rf ./physics_kinematic/assets/text24.font
rm -rf ./animation_spinner/assets/text24.font
rm -rf ./debug_physics/assets/text24.font
rm -rf ./gui_load_texture/assets/text24.font
rm -rf ./gui_drag/assets/text24.font
rm -rf ./gui_pointer_over/assets/text24.font
rm -rf ./factory_dynamic/assets/text24.font
rm -rf ./factory_basic/assets/text24.font
rm -rf ./basics_parent_child/assets/text24.font
rm -rf ./animation_basic_tween/assets/text24.font
rm -rf ./movement_move_to/assets/text24.font
rm -rf ./factory_bullets/assets/text24.font
rm -rf ./input_move/assets/text24.font
rm -rf ./collection_timestep/assets/text24.font
rm -rf ./movement_movement_speed/assets/text24.font
rm -rf ./particles_modifiers/assets/text24.font
rm -rf ./input_down_duration/assets/text24.font
rm -rf ./gui_text_input/assets/text24.font
rm -rf ./gui_color/assets/text24.font
rm -rf ./gui_button/assets/text24.font
rm -rf ./animation_cursor/assets/text24.font
rm -rf ./animation_chained_tween/assets/text24.font
rm -rf ./sound_music/assets/text24.font
rm -rf ./physics_dynamic/assets/text24.font
rm -rf ./basics_z_order/assets/text24.font
rm -rf ./physics_trigger/assets/text24.font
rm -rf ./particles_confetti/assets/text24.font
rm -rf ./animation_flipbook/assets/text24.font
rm -rf ./resource_create_atlas/assets/text24.font
rm -rf ./resource_modify_atlas/assets/text24.font
rm -rf ./render_screen_to_world/assets/text24.font
rm -rf ./sprite_size/assets/text24.font
rm -rf ./movement_follow/assets/text24.font
rm -rf ./movement_simple_move/assets/text24.font
rm -rf ./particles_fire_and_smoke/assets/text24.font
rm -rf ./sprite_bunnymark/assets/text24.font
rm -rf ./gui_get_set_font/assets/text24.font
rm -rf ./physics_hinge_joint/assets/text24.font
rm -rf ./particles_fireworks/assets/text24.font
