rm -rf ./render_camera/assets/images/fireworks
rm -rf ./animation_spine/assets/images/fireworks
rm -rf ./material_noise/assets/images/fireworks
rm -rf ./animation_chained_flipbook/assets/images/fireworks
rm -rf ./gui_healthbar/assets/images/fireworks
rm -rf ./input_mouse_and_touch/assets/images/fireworks
rm -rf ./collection_proxy/assets/images/fireworks
rm -rf ./gui_stencil/assets/images/fireworks
rm -rf ./timer_repeating_timer/assets/images/fireworks
rm -rf ./physics_knockback/assets/images/fireworks
rm -rf ./movement_look_at/assets/images/fireworks
rm -rf ./movement_look_rotation/assets/images/fireworks
rm -rf ./tilemap_collisions/assets/images/fireworks
rm -rf ./physics_pendulum/assets/images/fireworks
rm -rf ./mesh_triangle/assets/images/fireworks
rm -rf ./debug_profile/assets/images/fireworks
rm -rf ./particles_particlefx/assets/images/fireworks
rm -rf ./model_cubemap/assets/images/fireworks
rm -rf ./sprite_tint/assets/images/fireworks
rm -rf ./movement_move_forward/assets/images/fireworks
rm -rf ./sprite_flip/assets/images/fireworks
rm -rf ./material_screenspace/assets/images/fireworks
rm -rf ./gui_get_set_texture/assets/images/fireworks
rm -rf ./render_orbit_camera/assets/images/fireworks
rm -rf ./material_vertexcolor/assets/images/fireworks
rm -rf ./material_unlit/assets/images/fireworks
rm -rf ./physics_raycast/assets/images/fireworks
rm -rf ./sound_fade_in_out/assets/images/fireworks
rm -rf ./material_uvgradient/assets/images/fireworks
rm -rf ./sound_panning/assets/images/fireworks
rm -rf ./input_text/assets/images/fireworks
rm -rf ./basics_message_passing/assets/images/fireworks
rm -rf ./timer_trigger_timer/assets/images/fireworks
rm -rf ./animation_euler_rotation/assets/images/fireworks
rm -rf ./gui_slice9/assets/images/fireworks
rm -rf ./file_sys_save_load/assets/images/fireworks
rm -rf ./physics_kinematic/assets/images/fireworks
rm -rf ./animation_spinner/assets/images/fireworks
rm -rf ./gui_progress/assets/images/fireworks
rm -rf ./debug_physics/assets/images/fireworks
rm -rf ./gui_load_texture/assets/images/fireworks
rm -rf ./gui_get_set_material/assets/images/fireworks
rm -rf ./gui_drag/assets/images/fireworks
rm -rf ./gui_pointer_over/assets/images/fireworks
rm -rf ./factory_dynamic/assets/images/fireworks
rm -rf ./factory_basic/assets/images/fireworks
rm -rf ./basics_parent_child/assets/images/fireworks
rm -rf ./animation_basic_tween/assets/images/fireworks
rm -rf ./movement_move_to/assets/images/fireworks
rm -rf ./factory_bullets/assets/images/fireworks
rm -rf ./input_move/assets/images/fireworks
rm -rf ./collection_timestep/assets/images/fireworks
rm -rf ./movement_movement_speed/assets/images/fireworks
rm -rf ./particles_modifiers/assets/images/fireworks
rm -rf ./input_down_duration/assets/images/fireworks
rm -rf ./gui_text_input/assets/images/fireworks
rm -rf ./gui_color/assets/images/fireworks
rm -rf ./collection_splash/assets/images/fireworks
rm -rf ./gui_button/assets/images/fireworks
rm -rf ./gui_layouts/assets/images/fireworks
rm -rf ./animation_cursor/assets/images/fireworks
rm -rf ./animation_chained_tween/assets/images/fireworks
rm -rf ./sound_music/assets/images/fireworks
rm -rf ./physics_dynamic/assets/images/fireworks
rm -rf ./basics_z_order/assets/images/fireworks
rm -rf ./physics_trigger/assets/images/fireworks
rm -rf ./particles_confetti/assets/images/fireworks
rm -rf ./animation_flipbook/assets/images/fireworks
rm -rf ./resource_create_atlas/assets/images/fireworks
rm -rf ./resource_modify_atlas/assets/images/fireworks
rm -rf ./render_screen_to_world/assets/images/fireworks
rm -rf ./timer_cancel_timer/assets/images/fireworks
rm -rf ./sprite_size/assets/images/fireworks
rm -rf ./movement_follow/assets/images/fireworks
rm -rf ./movement_simple_move/assets/images/fireworks
rm -rf ./particles_fire_and_smoke/assets/images/fireworks
rm -rf ./tilemap_get_set_tile/assets/images/fireworks
rm -rf ./sprite_bunnymark/assets/images/fireworks
rm -rf ./gui_get_set_font/assets/images/fireworks
rm -rf ./physics_hinge_joint/assets/images/fireworks
rm -rf ./animation_easing/assets/images/fireworks
