rm -rf ./render_camera/assets/random_images
rm -rf ./animation_spine/assets/random_images
rm -rf ./material_noise/assets/random_images
rm -rf ./animation_chained_flipbook/assets/random_images
rm -rf ./gui_healthbar/assets/random_images
rm -rf ./input_mouse_and_touch/assets/random_images
rm -rf ./collection_proxy/assets/random_images
rm -rf ./gui_stencil/assets/random_images
rm -rf ./timer_repeating_timer/assets/random_images
rm -rf ./physics_knockback/assets/random_images
rm -rf ./movement_look_at/assets/random_images
rm -rf ./movement_look_rotation/assets/random_images
rm -rf ./tilemap_collisions/assets/random_images
rm -rf ./physics_pendulum/assets/random_images
rm -rf ./mesh_triangle/assets/random_images
rm -rf ./debug_profile/assets/random_images
rm -rf ./particles_particlefx/assets/random_images
rm -rf ./model_cubemap/assets/random_images
rm -rf ./sprite_tint/assets/random_images
rm -rf ./movement_move_forward/assets/random_images
rm -rf ./sprite_flip/assets/random_images
rm -rf ./material_screenspace/assets/random_images
rm -rf ./gui_get_set_texture/assets/random_images
rm -rf ./render_orbit_camera/assets/random_images
rm -rf ./material_vertexcolor/assets/random_images
rm -rf ./material_unlit/assets/random_images
rm -rf ./physics_raycast/assets/random_images
rm -rf ./sound_fade_in_out/assets/random_images
rm -rf ./material_uvgradient/assets/random_images
rm -rf ./sound_panning/assets/random_images
rm -rf ./input_text/assets/random_images
rm -rf ./basics_message_passing/assets/random_images
rm -rf ./timer_trigger_timer/assets/random_images
rm -rf ./animation_euler_rotation/assets/random_images
rm -rf ./gui_slice9/assets/random_images
rm -rf ./file_sys_save_load/assets/random_images
rm -rf ./physics_kinematic/assets/random_images
rm -rf ./animation_spinner/assets/random_images
rm -rf ./gui_progress/assets/random_images
rm -rf ./debug_physics/assets/random_images
rm -rf ./gui_load_texture/assets/random_images
rm -rf ./gui_get_set_material/assets/random_images
rm -rf ./gui_drag/assets/random_images
rm -rf ./gui_pointer_over/assets/random_images
rm -rf ./factory_dynamic/assets/random_images
rm -rf ./factory_basic/assets/random_images
rm -rf ./basics_parent_child/assets/random_images
rm -rf ./animation_basic_tween/assets/random_images
rm -rf ./movement_move_to/assets/random_images
rm -rf ./factory_bullets/assets/random_images
rm -rf ./input_move/assets/random_images
rm -rf ./collection_timestep/assets/random_images
rm -rf ./movement_movement_speed/assets/random_images
rm -rf ./particles_modifiers/assets/random_images
rm -rf ./input_down_duration/assets/random_images
rm -rf ./gui_text_input/assets/random_images
rm -rf ./gui_color/assets/random_images
rm -rf ./collection_splash/assets/random_images
rm -rf ./gui_button/assets/random_images
rm -rf ./gui_layouts/assets/random_images
rm -rf ./animation_cursor/assets/random_images
rm -rf ./animation_chained_tween/assets/random_images
rm -rf ./sound_music/assets/random_images
rm -rf ./physics_dynamic/assets/random_images
rm -rf ./basics_z_order/assets/random_images
rm -rf ./physics_trigger/assets/random_images
rm -rf ./particles_confetti/assets/random_images
rm -rf ./animation_flipbook/assets/random_images
rm -rf ./resource_create_atlas/assets/random_images
rm -rf ./resource_modify_atlas/assets/random_images
rm -rf ./render_screen_to_world/assets/random_images
rm -rf ./timer_cancel_timer/assets/random_images
rm -rf ./sprite_size/assets/random_images
rm -rf ./movement_follow/assets/random_images
rm -rf ./movement_simple_move/assets/random_images
rm -rf ./particles_fire_and_smoke/assets/random_images
rm -rf ./tilemap_get_set_tile/assets/random_images
rm -rf ./sprite_bunnymark/assets/random_images
rm -rf ./gui_get_set_font/assets/random_images
rm -rf ./physics_hinge_joint/assets/random_images
rm -rf ./particles_fireworks/assets/random_images
rm -rf ./animation_easing/assets/random_images
