embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/main/AnimationLibrary_Standard.glb\"\n"
  "skeleton: \"/main/AnimationLibrary_Standard.glb\"\n"
  "animations: \"/main/AnimationLibrary_Standard.glb\"\n"
  "default_animation: \"A_TPose\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"M_Joints\"\n"
  "  material: \"/builtins/materials/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/main/man.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"M_Main\"\n"
  "  material: \"/builtins/materials/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/main/man.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
